name: localizely_sdk
description: Localizely SDK for Flutter enables Over-the-air translations update from Localizely cloud platform
version: 2.7.5
homepage: https://localizely.com/flutter-over-the-air/

topics:
  - i18n
  - internationalization
  - l10n
  - localization

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ">=3.0.0 <5.0.0"
  build_config: ^1.0.0
  glob: ^2.0.0
  intl: ">=0.18.0 <0.21.0"
  http: ">=0.13.0 <2.0.0"
  logger: ^2.0.0
  path: ^1.8.0
  package_info_plus: ">=8.0.0 <10.0.0"
  path_provider: ^2.0.0
  petitparser: ">=4.0.0 <8.0.0"
  shared_preferences: ^2.3.4
  uuid: ^4.0.0
  web_socket_channel: ^3.0.0
  yaml: ^3.0.0
  web: ^1.0.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^6.0.0
  mockito: ^5.4.0
  test: ^1.25.0

flutter:
  assets:
    - assets/images/localizely-logo.png
    - assets/images/2.0x/localizely-logo.png
    - assets/images/3.0x/localizely-logo.png
