name: version_manipulation
version: 0.2.0
homepage: https://github.com/f3ath/dart-version-manipulation
description: Extension on Dart `pub_semver` library. Provides `nextBuild`, `nextPreRelease` and `change`.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  pub_semver: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  coverage: ^1.0.1
  check_coverage: ^0.0.2

cider:
  link_template:
    tag: https://github.com/f3ath/dart-version-manipulation/releases/tag/%tag%
    diff: https://github.com/f3ath/dart-version-manipulation/compare/%from%...%to%