name: threed_print_cost_calculator
description: A simple 3D Print cost calculator.
version: 2.3.0+3
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  bloc: 9.2.0
  bot_toast: 4.1.3
  cider: 0.2.10
  device_check: 1.0.0
  equatable: 2.0.8
  firebase_analytics: 12.1.2
  firebase_app_check: 0.4.1+4
  firebase_core: 4.4.0
  firebase_crashlytics: 5.0.7
  flutter:
    sdk: flutter
  formz: 0.8.0
  flutter_hooks: 0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 3.2.1
  flutter_slidable: 4.0.3
  hooks_riverpod: 3.2.1
  intl: 0.20.2
  localizely_sdk: 2.7.5
  path:
  path_provider: 2.1.5
  platform_info: 5.0.0
  purchases_flutter: 9.12.0
  purchases_ui_flutter: 9.12.0
  rate_my_app: 2.3.2
  riverpod: 3.2.1
  sembast: 3.8.6
  shared_preferences: 2.5.4
  share_plus: 12.0.1
  url_launcher: 6.3.2

dev_dependencies:
  bloc_test: 10.0.0
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  flutter_lints: 6.0.0
  shared_preferences_platform_interface:


dependency_overrides:
  intl: 0.20.2

flutter:
  uses-material-design: true
  generate: true

cider:
  link_template:
    tag: https://github.com/RemeJuan/threed_print_cost_calculator/releases/tag/%tag% # initial release link template
    diff: https://github.com/RemeJuan/threed_print_cost_calculator/compare/%from%...%to% # subsequent releases link template

flutter_intl:
  enabled: true
  localizely:
    ota_enabled: false
    project_id: 268cbebb-6c43-4716-a4b0-4d4217db93df
